### ISSUE TITLE
location doesn't work on ungoogled chromium

### ISSUE THREAD

**Issue by k2662** [fvrests/lavender#33]

**Comment by fvrests** [comment]
Unfortunately, I think this is an upstream issue with ungoogled-chromium per [#1551](https://github.com/ungoogled-software/ungoogled-chromium/issues/1551), as it seems the browser prevents usage of the Geolocation API. 

A commenter on that issue did suggest a [workaround with location spoofing](https://github.com/ungoogled-software/ungoogled-chromium/issues/1551#issuecomment-1738237814), I’d recommend to give that a try and see if it at least allows a manual override of your location data.

**Comment by k2662** [comment]
> Unfortunately, I think this is an upstream issue with ungoogled-chromium per [#1551](https://github.com/ungoogled-software/ungoogled-chromium/issues/1551), as it seems the browser prevents usage of the Geolocation API.
> 
> A commenter on that issue did suggest a [workaround with location spoofing](https://github.com/ungoogled-software/ungoogled-chromium/issues/1551#issuecomment-1738237814), I’d recommend to give that a try and see if it at least allows a manual override of your location data.

yeah found that out after doing research. Almost all modern browsers have location services of some kind, so the fact that it doesn't is dysfunctional.

**Comment by fvrests** [comment]
Hoping you'll give it another go if you end up choosing another browser! Feel free to reach out again if you run into any other issues. :)

**Comment by k2662** [comment]
> Hoping you'll give it another go if you end up choosing another browser! Feel free to reach out again if you run into any other issues. :)

I use brave now and it works really well :)
